# Generated by Django 5.0.6 on 2024-06-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 37, 37, 984954, tzinfo=datetime.timezone.utc)),
        ),
    ]
