# Generated by Django 5.0.6 on 2024-06-09 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_verificationcodes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 39, 44, 535271, tzinfo=datetime.timezone.utc)),
        ),
    ]
