# Generated by Django 5.0.6 on 2024-06-09 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_verificationcodes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 11, 47, 46, 752812, tzinfo=datetime.timezone.utc)),
        ),
    ]
