# Generated by Django 5.0.6 on 2024-06-10 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_vote_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 16, 10, 35, 882820, tzinfo=datetime.timezone.utc)),
        ),
    ]
