# Generated by Django 5.0.6 on 2024-06-10 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_verificationcodes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 16, 54, 59, 17710, tzinfo=datetime.timezone.utc)),
        ),
    ]
