# Generated by Django 5.0.6 on 2024-06-10 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_verificationcodes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 20, 23, 42, 760579, tzinfo=datetime.timezone.utc)),
        ),
    ]
