# Generated by Django 5.0.6 on 2024-06-10 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_verificationcodes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 21, 2, 35, 3935, tzinfo=datetime.timezone.utc)),
        ),
    ]
