# Generated by Django 5.0.6 on 2024-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_poll_allowed_voters_pollwallet_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='avatar',
            field=models.ImageField(blank=True, default='polls/default.jpg', null=True, upload_to='polls/'),
        ),
    ]
