# Generated by Django 5.0.6 on 2024-06-10 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_poll_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
