# Generated by Django 5.0.6 on 2024-06-10 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_poll_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.poll')),
            ],
            options={
                'verbose_name': 'Poll Invitation',
                'verbose_name_plural': 'Poll Invitations',
            },
        ),
    ]
