# Generated by Django 5.0.6 on 2024-06-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_pollinvitation_is_declined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='candidates',
        ),
        migrations.CreateModel(
            name='PollCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_coins', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.poll')),
            ],
            options={
                'verbose_name': 'Poll Candidate',
                'verbose_name_plural': 'Poll Candidates',
            },
        ),
    ]
